# Generated by Django 2.2.5 on 2019-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('address', models.CharField(default=0, max_length=500)),
                ('contact', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=300)),
                ('total_price', models.CharField(max_length=300)),
                ('total_units', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invi_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('units_load', models.IntegerField()),
                ('no_loads', models.IntegerField()),
                ('tot_units', models.IntegerField()),
                ('tot_price', models.IntegerField()),
            ],
        ),
    ]
