# Generated by Django 2.2.5 on 2019-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField(unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('address', models.CharField(default=0, max_length=500)),
                ('contact', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=300)),
                ('total_price', models.CharField(max_length=300)),
                ('total_units', models.CharField(max_length=300)),
            ],
        ),
    ]
