# Generated by Django 2.2.5 on 2019-09-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='invi_id',
            new_name='inv_id',
        ),
    ]
