# Generated by Django 2.2.5 on 2019-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='inv_id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
