# Generated by Django 2.2.5 on 2019-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190918_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('units_load', models.IntegerField()),
                ('no_loads', models.IntegerField()),
                ('tot_units', models.IntegerField()),
                ('tot_price', models.IntegerField()),
            ],
        ),
    ]
