# Generated by Django 2.2.5 on 2019-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190909_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='Description',
            field=models.CharField(default='Site', max_length=500),
        ),
    ]
