# Generated by Django 2.2.5 on 2019-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_sites_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
